import {
  mkdtempSync,
  mkdirSync,
  writeFileSync,
  readFileSync,
  rmSync,
  existsSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { afterEach, expect, test } from "vitest";
const fixtures = [];
afterEach(() =>
  fixtures
    .splice(0)
    .forEach((path) => rmSync(path, { recursive: true, force: true })),
);
function fixture(desktop = 900, rowMin = 80) {
  const root = mkdtempSync(join(tmpdir(), "f1-home-fidelity-"));
  fixtures.push(root);
  mkdirSync(join(root, "scripts"));
  mkdirSync(join(root, "src/design-system"), { recursive: true });
  const script = resolve("scripts/generate-home-fidelity.js");
  if (existsSync(script))
    writeFileSync(
      join(root, "scripts/generate-home-fidelity.js"),
      readFileSync(script),
    );
  writeFileSync(join(root, "package.json"), '{"type":"module"}');
  writeFileSync(
    join(root, "src/design-system/apex.tokens.json"),
    JSON.stringify({
      homeFidelity: {
        desktopMinWidth: desktop,
        championshipPreviewRowMinHeight: rowMin,
      },
    }),
  );
  const original =
    ":root {\n  --apex-size-home-championship-preview-row-min: 1px;\n}\n/* Home desktop breakpoint */\n@media (min-width: 200px) {}\n";
  const output = join(root, "src/design-system/home-fidelity.css");
  writeFileSync(output, original);
  return {
    output,
    original,
    run: () =>
      spawnSync(
        process.execPath,
        [join(root, "scripts/generate-home-fidelity.js")],
        { encoding: "utf8" },
      ),
  };
}
test("Home media aliases are generated by key and byte-idempotent", () => {
  const { output, run } = fixture();
  expect(run().status).toBe(0);
  const first = readFileSync(output, "utf8");
  expect(first).toContain("min-width: 900px");
  expect(first).toContain(
    "--apex-size-home-championship-preview-row-min: 80px;",
  );
  expect(run().status).toBe(0);
  expect(readFileSync(output, "utf8")).toBe(first);
});
test.each([0, 380.5, Infinity, NaN])(
  "invalid Home breakpoint %s changes no output",
  (value) => {
    const { output, original, run } = fixture(value);
    expect(run().status).not.toBe(0);
    expect(readFileSync(output, "utf8")).toBe(original);
  },
);
test.each([0, -1, 104.5, Infinity, NaN, "104", 1e300])(
  "invalid preview row minimum %s changes no output",
  (value) => {
    const { output, original, run } = fixture(900, value);
    expect(run().status).not.toBe(0);
    expect(readFileSync(output, "utf8")).toBe(original);
  },
);
