// Reviewed local flag-icons v7.5.0 (MIT), 4x3 SVG subset; no runtime CDN dependency.
export const countryFlagAssets = Object.freeze(
  Object.fromEntries(
    [
      "AU",
      "AT",
      "AZ",
      "BE",
      "BR",
      "CA",
      "CN",
      "HU",
      "IT",
      "JP",
      "MY",
      "MX",
      "MC",
      "NL",
      "QA",
      "SG",
      "ES",
      "AE",
      "GB",
      "US",
      "BH",
      "SA",
      "FR",
      "DE",
      "PT",
      "TR",
      "KR",
      "IN",
      "AR",
      "ZA",
    ].map((code) => [code, `/images/flags/${code.toLowerCase()}.svg`]),
  ),
);
